global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'  # 使用 QQ 邮箱的 SSL 加密端口
  smtp_from: 'your_email@qq.com'  # 发件人邮箱（需真实存在）
  smtp_auth_username: 'your_email@qq.com'  # 认证邮箱（与发件人一致）
  smtp_auth_password: 'YOUR_QQ_AUTH_CODE'  # QQ 邮箱授权码（非登录密码）
  smtp_require_tls: false  # 465 端口禁用 STARTTLS
  smtp_hello: 'qq.com'  # 握手标识符

route:
  group_by: ['alertname']  # 按告警名称分组
  group_wait: 30s  # 新警报等待 30 秒后发送
  group_interval: 5m  # 同组警报间隔 5 分钟
  repeat_interval: 1h  # 未解决警报每 1 小时重发
  receiver: 'email-notice'  # 默认发送到邮件接收器
receivers:
  - name: 'email-notice'  # 接收器名称
    email_configs:
      - to: 'your_email@example.com'  # 收件人地址
        send_resolved: true  # 发送恢复通知
